// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDuFFnL1m2IK82o0TLv3MO8qQJYqW39kw',
    appId: '1:198576532701:web:375ceb4ab64db8d655ff34',
    messagingSenderId: '198576532701',
    projectId: 'ecommerce-app-b59ad',
    authDomain: 'ecommerce-app-b59ad.firebaseapp.com',
    storageBucket: 'ecommerce-app-b59ad.appspot.com',
    measurementId: 'G-9YJ46608LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3yN-6YduVU75A4qXI_AyWYAMqvP4Ei4Q',
    appId: '1:198576532701:android:c5cec9dc63d5df3955ff34',
    messagingSenderId: '198576532701',
    projectId: 'ecommerce-app-b59ad',
    storageBucket: 'ecommerce-app-b59ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmeMQm0KaKwA0HgkZFXA9t9sAbXXsbn7E',
    appId: '1:198576532701:ios:bb2edd5993816b0b55ff34',
    messagingSenderId: '198576532701',
    projectId: 'ecommerce-app-b59ad',
    storageBucket: 'ecommerce-app-b59ad.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmeMQm0KaKwA0HgkZFXA9t9sAbXXsbn7E',
    appId: '1:198576532701:ios:bb2edd5993816b0b55ff34',
    messagingSenderId: '198576532701',
    projectId: 'ecommerce-app-b59ad',
    storageBucket: 'ecommerce-app-b59ad.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDuFFnL1m2IK82o0TLv3MO8qQJYqW39kw',
    appId: '1:198576532701:web:b9c4d8d22f2c8fef55ff34',
    messagingSenderId: '198576532701',
    projectId: 'ecommerce-app-b59ad',
    authDomain: 'ecommerce-app-b59ad.firebaseapp.com',
    storageBucket: 'ecommerce-app-b59ad.appspot.com',
    measurementId: 'G-G8J8CVLYKJ',
  );
}
